import {
  User,
  Course,
  Enrollment,
  Order,
  Payment,
  Coupon,
  AccessCode,
  AccessCodeRedemption,
  AppNotification,
  Analytics,
} from '../types';

export const mockCurrentUserStudent: User = {
  id: 'usr_student_01',
  name: 'Alex Rivera',
  email: 'alex.rivera@example.com',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
  role: 'student',
  headline: 'Senior Frontend Engineer & Lifelong Learner',
  bio: 'Specializing in reactive systems, modern design systems, and distributed platforms.',
  joinedAt: '2025-11-14T09:00:00Z',
  timezone: 'America/New_York (UTC-5)',
  enrolledCourseIds: ['course_01', 'course_02'],
};

export const mockCurrentUserAdmin: User = {
  id: 'usr_admin_01',
  name: 'Elena Vance',
  email: 'elena.vance@creatoracademy.io',
  avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
  role: 'admin',
  headline: 'Founder & Principal Systems Architect',
  bio: 'Author of Cloud Architecture Handbook. Building private mastery curriculums for engineers.',
  joinedAt: '2024-01-10T10:00:00Z',
  timezone: 'America/San_Francisco (UTC-8)',
  enrolledCourseIds: [],
};

export const mockCourses: Course[] = [
  {
    id: 'course_01',
    title: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    slug: 'fullstack-cloud-architecture',
    shortDescription: 'Master modern cloud patterns, event-driven design, and resilient multi-region architectures.',
    fullDescription: 'A private comprehensive curriculum taking you from standard monoliths to battle-tested distributed architectures. Covers state machines, idempotent API routing, zero-trust container orchestration, and real-time reactive frontends.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    price: 349,
    currency: 'USD',
    status: 'published',
    instructor: {
      id: 'usr_admin_01',
      name: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
      title: 'Principal Systems Architect',
    },
    category: 'Engineering & Cloud',
    level: 'Advanced',
    totalDurationMinutes: 520,
    modulesCount: 4,
    lessonsCount: 16,
    enrolledStudentsCount: 384,
    rating: 4.95,
    reviewsCount: 142,
    updatedAt: '2026-03-12T14:00:00Z',
    learningOutcomes: [
      'Design idempotent asynchronous distributed workflows',
      'Orchestrate secure containerized micro-frontends with edge routing',
      'Implement real-time telemetry, trace propagation, and chaos testing',
      'Optimize egress network latency and multi-region database replication',
    ],
    prerequisites: ['Proficiency in TypeScript or Node.js', 'Foundational understanding of HTTP/REST and Docker'],
    modules: [
      {
        id: 'mod_01',
        courseId: 'course_01',
        title: 'Module 1: Foundations of Resilient Cloud Infrastructure',
        description: 'Core concepts of stateless compute, network partitioning, and zero-trust perimeter.',
        order: 1,
        lessons: [
          {
            id: 'les_01_01',
            moduleId: 'mod_01',
            courseId: 'course_01',
            title: 'Architectural Philosophy: Stateless vs Authoritative Nodes',
            description: 'Deconstructing traditional session-bound architectures into stateless edge workers.',
            order: 1,
            durationMinutes: 24,
            isFreePreview: true,
            video: {
              id: 'vid_01_01',
              title: 'Stateless vs Authoritative Nodes',
              durationSeconds: 1440,
              isProcessed: true,
              resolution: '4K / 60fps',
              watermarkText: 'ALEX RIVERA • 2026-09-22',
            },
            resourcesCount: 2,
            attachments: [
              { id: 'att_1', name: 'Stateless_Design_Checklist.pdf', size: '2.4 MB', type: 'PDF' },
              { id: 'att_2', name: 'architecture_diagrams.figma', size: '5.1 MB', type: 'Figma' },
            ],
          },
          {
            id: 'les_01_02',
            moduleId: 'mod_01',
            courseId: 'course_01',
            title: 'Network Topologies, VPC Peering & Zero-Trust Ingress',
            description: 'Building secure isolated subnets and enforcing mTLS between internal services.',
            order: 2,
            durationMinutes: 32,
            isFreePreview: false,
            video: {
              id: 'vid_01_02',
              title: 'VPC Peering & Zero-Trust Ingress',
              durationSeconds: 1920,
              isProcessed: true,
              resolution: '1080p',
              watermarkText: 'ALEX RIVERA • 2026-09-22',
            },
            resourcesCount: 1,
          },
          {
            id: 'les_01_03',
            moduleId: 'mod_01',
            courseId: 'course_01',
            title: 'Container Lifecycle, Cold Starts & Health Probes',
            description: 'Tuning Kubernetes and Cloud Run containers for sub-100ms startup times.',
            order: 3,
            durationMinutes: 28,
            video: {
              id: 'vid_01_03',
              title: 'Container Lifecycle & Probes',
              durationSeconds: 1680,
              isProcessed: true,
            },
          },
          {
            id: 'les_01_04',
            moduleId: 'mod_01',
            courseId: 'course_01',
            title: 'Hands-on Lab: Deploying Multi-Zone Micro-Services',
            description: 'Live interactive coding of a resilient edge routing cluster.',
            order: 4,
            durationMinutes: 45,
            video: {
              id: 'vid_01_04',
              title: 'Deploying Multi-Zone Micro-Services',
              durationSeconds: 2700,
              isProcessed: true,
            },
          },
        ],
      },
      {
        id: 'mod_02',
        courseId: 'course_01',
        title: 'Module 2: Event-Driven Systems & Transactional Outbox',
        description: 'Preventing split-brain states and ensuring dual-write integrity under failure.',
        order: 2,
        lessons: [
          {
            id: 'les_02_01',
            moduleId: 'mod_02',
            courseId: 'course_01',
            title: 'The Dual-Write Problem & Transactional Outbox Pattern',
            order: 1,
            durationMinutes: 38,
            video: {
              id: 'vid_02_01',
              title: 'Dual-Write Problem & Outbox Pattern',
              durationSeconds: 2280,
              isProcessed: true,
            },
          },
          {
            id: 'les_02_02',
            moduleId: 'mod_02',
            courseId: 'course_01',
            title: 'Message Brokers: Kafka vs RabbitMQ vs Pub/Sub in Practice',
            order: 2,
            durationMinutes: 35,
            video: {
              id: 'vid_02_02',
              title: 'Broker Benchmark Analysis',
              durationSeconds: 2100,
              isProcessed: true,
            },
          },
          {
            id: 'les_02_03',
            moduleId: 'mod_02',
            courseId: 'course_01',
            title: 'Sagas, Compensation Flows & Dead Letter Queue Triage',
            order: 3,
            durationMinutes: 40,
            video: {
              id: 'vid_02_03',
              title: 'Distributed Sagas & Dead Letters',
              durationSeconds: 2400,
              isProcessed: true,
            },
          },
        ],
      },
      {
        id: 'mod_03',
        courseId: 'course_01',
        title: 'Module 3: Scalable Frontend Orchestration',
        description: 'Designing independent team deployment boundaries with micro-frontends.',
        order: 3,
        lessons: [
          {
            id: 'les_03_01',
            moduleId: 'mod_03',
            courseId: 'course_01',
            title: 'Module Federation vs Iframe Sandbox Isolation',
            order: 1,
            durationMinutes: 30,
            video: {
              id: 'vid_03_01',
              title: 'Module Federation deep-dive',
              durationSeconds: 1800,
              isProcessed: true,
            },
          },
          {
            id: 'les_03_02',
            moduleId: 'mod_03',
            courseId: 'course_01',
            title: 'Unified Design Token Pipeline and CSS Scoping',
            order: 2,
            durationMinutes: 26,
            video: {
              id: 'vid_03_02',
              title: 'Token Pipelines',
              durationSeconds: 1560,
              isProcessed: true,
            },
          },
        ],
      },
      {
        id: 'mod_04',
        courseId: 'course_01',
        title: 'Module 4: Production Observability & Chaos Engineering',
        description: 'Automated synthetic traffic, canary rollback gates, and real-user monitoring.',
        order: 4,
        lessons: [
          {
            id: 'les_04_01',
            moduleId: 'mod_04',
            courseId: 'course_01',
            title: 'Distributed Tracing with OpenTelemetry across Microservices',
            order: 1,
            durationMinutes: 42,
            video: {
              id: 'vid_04_01',
              title: 'OpenTelemetry Setup',
              durationSeconds: 2520,
              isProcessed: true,
            },
          },
          {
            id: 'les_04_02',
            moduleId: 'mod_04',
            courseId: 'course_01',
            title: 'Running Chaos Drills and Automated Canary Rollbacks',
            order: 2,
            durationMinutes: 36,
            video: {
              id: 'vid_04_02',
              title: 'Chaos Drills & Canaries',
              durationSeconds: 2160,
              isProcessed: true,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'course_02',
    title: 'High-Performance UI Design Systems & Component Architecture',
    slug: 'high-performance-ui-systems',
    shortDescription: 'Build scalable, accessible, design-token driven design systems with Tailwind CSS.',
    fullDescription: 'Comprehensive guide to modern component architecture, headless primitives, accessible keyboard navigation, mathematical typography scales, and token-based enterprise design systems.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
    price: 279,
    currency: 'USD',
    status: 'published',
    instructor: {
      id: 'usr_admin_01',
      name: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
      title: 'Principal Systems Architect',
    },
    category: 'Design & Frontend',
    level: 'Intermediate',
    totalDurationMinutes: 380,
    modulesCount: 3,
    lessonsCount: 11,
    enrolledStudentsCount: 512,
    rating: 4.98,
    reviewsCount: 204,
    updatedAt: '2026-03-10T11:00:00Z',
    learningOutcomes: [
      'Master token-driven dynamic theming and mathematical spacing scales',
      'Implement full WCAG AAA accessible focus rings and keyboard navigation',
      'Optimize React rendering performance with headless state machines',
    ],
    prerequisites: ['Solid React and CSS fundamentals'],
    modules: [
      {
        id: 'mod_201',
        courseId: 'course_02',
        title: 'Module 1: Design Tokens & Visual Hierarchy',
        order: 1,
        lessons: [
          {
            id: 'les_201_01',
            moduleId: 'mod_201',
            courseId: 'course_02',
            title: 'Mathematical Typography & Optical Harmony',
            order: 1,
            durationMinutes: 28,
            isFreePreview: true,
            video: {
              id: 'vid_201_01',
              title: 'Typography & Optical Balance',
              durationSeconds: 1680,
              isProcessed: true,
            },
          },
          {
            id: 'les_201_02',
            moduleId: 'mod_201',
            courseId: 'course_02',
            title: 'Constructing Scalable Color Tokens with HSB Bounds',
            order: 2,
            durationMinutes: 34,
            video: {
              id: 'vid_201_02',
              title: 'HSB Color Token Architecture',
              durationSeconds: 2040,
              isProcessed: true,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'course_03',
    title: 'Applied AI Engineering & Production LLMOps Frameworks',
    slug: 'applied-ai-engineering-llmops',
    shortDescription: 'Production engineering for agentic workflows, deterministic evaluations, and inference optimization.',
    fullDescription: 'Learn how to take LLM prototypes into production with strict latency budgets, hybrid vector indexing, tool calling, and guardrail enforcement.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    price: 499,
    currency: 'USD',
    status: 'published',
    instructor: {
      id: 'usr_admin_01',
      name: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
      title: 'Principal Systems Architect',
    },
    category: 'AI & Machine Learning',
    level: 'Advanced',
    totalDurationMinutes: 620,
    modulesCount: 5,
    lessonsCount: 18,
    enrolledStudentsCount: 228,
    rating: 4.92,
    reviewsCount: 89,
    updatedAt: '2026-03-18T16:30:00Z',
  },
  {
    id: 'course_04',
    title: 'Zero-Allocation Database Internals & Cache Hierarchies',
    slug: 'database-internals-cache-hierarchies',
    shortDescription: 'Deep dive into LSM trees, B-Trees, write-ahead logs, and memory allocation optimization.',
    fullDescription: 'Under-the-hood study of modern storage engines, memory mapping, lock-free concurrency, and distributed consensus.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    price: 399,
    currency: 'USD',
    status: 'draft',
    instructor: {
      id: 'usr_admin_01',
      name: 'Elena Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
      title: 'Principal Systems Architect',
    },
    category: 'Engineering & Cloud',
    level: 'Advanced',
    totalDurationMinutes: 440,
    modulesCount: 4,
    lessonsCount: 14,
    enrolledStudentsCount: 0,
    rating: 5.0,
    reviewsCount: 0,
    updatedAt: '2026-03-21T18:00:00Z',
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 'enr_01',
    studentId: 'usr_student_01',
    courseId: 'course_01',
    enrolledAt: '2026-01-15T12:00:00Z',
    status: 'active',
    accessSource: 'purchase',
    course: mockCourses[0],
    progress: {
      courseId: 'course_01',
      completedLessonIds: ['les_01_01', 'les_01_02'],
      lastLessonId: 'les_01_03',
      resumeSeconds: 420,
      totalLessons: 11,
      completedPercentage: 45,
      updatedAt: '2026-09-20T14:30:00Z',
    },
  },
  {
    id: 'enr_02',
    studentId: 'usr_student_01',
    courseId: 'course_02',
    enrolledAt: '2026-02-01T10:00:00Z',
    status: 'active',
    accessSource: 'access_code',
    course: mockCourses[1],
    progress: {
      courseId: 'course_02',
      completedLessonIds: ['les_201_01'],
      lastLessonId: 'les_201_02',
      resumeSeconds: 180,
      totalLessons: 6,
      completedPercentage: 20,
      updatedAt: '2026-09-18T18:15:00Z',
    },
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord_1001',
    orderNumber: 'ORD-2026-9812',
    studentId: 'usr_student_01',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@example.com',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    subtotal: 349,
    discountAmount: 50,
    total: 299,
    currency: 'USD',
    couponCode: 'LAUNCH50',
    status: 'completed',
    paymentMethod: 'Credit Card (•••• 4242)',
    createdAt: '2026-01-15T11:58:30Z',
  },
  {
    id: 'ord_1002',
    orderNumber: 'ORD-2026-9825',
    studentId: 'usr_student_02',
    studentName: 'Marcus Chen',
    studentEmail: 'marcus.chen@techcorp.io',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    subtotal: 349,
    discountAmount: 0,
    total: 349,
    currency: 'USD',
    status: 'completed',
    paymentMethod: 'Credit Card (•••• 8821)',
    createdAt: '2026-02-10T14:15:00Z',
  },
  {
    id: 'ord_1003',
    orderNumber: 'ORD-2026-9840',
    studentId: 'usr_student_03',
    studentName: 'Sarah Jenkins',
    studentEmail: 's.jenkins@enterprise.co',
    courseId: 'course_03',
    courseTitle: 'Applied AI Engineering & Production LLMOps Frameworks',
    subtotal: 499,
    discountAmount: 100,
    total: 399,
    currency: 'USD',
    couponCode: 'VIPFOUNDER',
    status: 'completed',
    paymentMethod: 'Corporate Wire / Card (•••• 1093)',
    createdAt: '2026-02-18T09:20:00Z',
  },
  {
    id: 'ord_1004',
    orderNumber: 'ORD-2026-9856',
    studentId: 'usr_student_04',
    studentName: 'David Kim',
    studentEmail: 'david.kim@startup.xyz',
    courseId: 'course_02',
    courseTitle: 'High-Performance UI Design Systems & Component Architecture',
    subtotal: 279,
    discountAmount: 0,
    total: 279,
    currency: 'USD',
    status: 'completed',
    paymentMethod: 'Credit Card (•••• 7734)',
    createdAt: '2026-03-01T16:45:00Z',
  },
  {
    id: 'ord_1005',
    orderNumber: 'ORD-2026-9871',
    studentId: 'usr_student_05',
    studentName: 'Priya Sharma',
    studentEmail: 'priya.s@devlead.org',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    subtotal: 349,
    discountAmount: 0,
    total: 349,
    currency: 'USD',
    status: 'failed',
    paymentMethod: 'Credit Card (•••• 0002)',
    createdAt: '2026-03-14T21:10:00Z',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay_901',
    orderId: 'ord_1001',
    studentId: 'usr_student_01',
    studentName: 'Alex Rivera',
    amount: 299,
    currency: 'USD',
    status: 'succeeded',
    provider: 'mock_stripe',
    transactionReference: 'ch_3N82Jd2eZvKYlo2C0198jK91',
    createdAt: '2026-01-15T11:58:32Z',
  },
  {
    id: 'pay_902',
    orderId: 'ord_1002',
    studentId: 'usr_student_02',
    studentName: 'Marcus Chen',
    amount: 349,
    currency: 'USD',
    status: 'succeeded',
    provider: 'mock_stripe',
    transactionReference: 'ch_3N82Kk4mQvLLpo8D9834mA22',
    createdAt: '2026-02-10T14:15:05Z',
  },
  {
    id: 'pay_903',
    orderId: 'ord_1003',
    studentId: 'usr_student_03',
    studentName: 'Sarah Jenkins',
    amount: 399,
    currency: 'USD',
    status: 'succeeded',
    provider: 'mock_stripe',
    transactionReference: 'ch_3N82Ln8xPvRRmo1F4490qW77',
    createdAt: '2026-02-18T09:20:04Z',
  },
  {
    id: 'pay_904',
    orderId: 'ord_1005',
    studentId: 'usr_student_05',
    studentName: 'Priya Sharma',
    amount: 349,
    currency: 'USD',
    status: 'failed',
    provider: 'mock_stripe',
    transactionReference: 'ch_3N82Pp9zIvSSww3M7712aE09',
    failureReason: 'Card issuer declined: Insufficient funds or fraud protection hold',
    createdAt: '2026-03-14T21:10:02Z',
  },
];

export const mockCoupons: Coupon[] = [
  {
    id: 'cpn_01',
    code: 'LAUNCH50',
    discountType: 'fixed',
    discountValue: 50,
    applicableCourseId: 'course_01',
    applicableCourseTitle: 'Fullstack Cloud Architecture',
    usageCount: 42,
    maxUses: 100,
    expiresAt: '2026-12-31T23:59:59Z',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'cpn_02',
    code: 'VIPFOUNDER',
    discountType: 'fixed',
    discountValue: 100,
    usageCount: 18,
    maxUses: 25,
    expiresAt: '2026-08-30T23:59:59Z',
    isActive: true,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'cpn_03',
    code: 'SPRING20',
    discountType: 'percentage',
    discountValue: 20,
    usageCount: 88,
    maxUses: 200,
    expiresAt: '2026-05-01T23:59:59Z',
    isActive: true,
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'cpn_04',
    code: 'EARLYBIRD',
    discountType: 'percentage',
    discountValue: 35,
    usageCount: 50,
    maxUses: 50,
    expiresAt: '2026-01-31T23:59:59Z',
    isActive: false,
    createdAt: '2025-12-01T00:00:00Z',
  },
];

export const mockAccessCodes: AccessCode[] = [
  {
    id: 'acc_01',
    code: 'CLOUD-PATRON-8841',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    allocatedToEmail: 'partner.lead@acmecorp.com',
    usageCount: 1,
    maxUses: 1,
    expiresAt: '2026-12-31T23:59:59Z',
    isActive: true,
    batchTag: 'Enterprise-Cohort-A',
    createdAt: '2026-01-10T12:00:00Z',
  },
  {
    id: 'acc_02',
    code: 'DESIGNSYS-STUDENT-4412',
    courseId: 'course_02',
    courseTitle: 'High-Performance UI Design Systems & Component Architecture',
    allocatedToEmail: 'alex.rivera@example.com',
    usageCount: 1,
    maxUses: 1,
    expiresAt: '2026-11-30T23:59:59Z',
    isActive: true,
    batchTag: 'Scholarship-Q1',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'acc_03',
    code: 'CORP-BULK-2026-001',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    usageCount: 14,
    maxUses: 20,
    expiresAt: '2026-09-30T23:59:59Z',
    isActive: true,
    batchTag: 'Fintech-Team-Pass',
    createdAt: '2026-02-05T09:30:00Z',
  },
  {
    id: 'acc_04',
    code: 'EXPIRED-PASS-0919',
    courseId: 'course_03',
    courseTitle: 'Applied AI Engineering & Production LLMOps Frameworks',
    usageCount: 5,
    maxUses: 5,
    expiresAt: '2026-02-15T23:59:59Z',
    isActive: false,
    batchTag: 'Beta-Reviewers',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'acc_05',
    code: 'CREATORHUB-INVITE-2026',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    usageCount: 0,
    maxUses: 50,
    expiresAt: '2027-12-31T23:59:59Z',
    isActive: true,
    batchTag: 'CreatorHub-Open-Invite',
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'acc_06',
    code: 'CADENCE-INVITE-2026',
    courseId: 'course_01',
    courseTitle: 'Fullstack Cloud Architecture & Scalable Micro-Frontends',
    usageCount: 0,
    maxUses: 50,
    expiresAt: '2027-12-31T23:59:59Z',
    isActive: true,
    batchTag: 'Legacy-Invite',
    createdAt: '2026-03-01T00:00:00Z',
  },
];

export const mockAccessCodeRedemptions: AccessCodeRedemption[] = [
  {
    id: 'red_01',
    codeId: 'acc_01',
    code: 'CLOUD-PATRON-8841',
    userId: 'usr_student_02',
    userEmail: 'marcus.chen@techcorp.io',
    courseId: 'course_01',
    redeemedAt: '2026-01-12T14:20:00Z',
  },
  {
    id: 'red_02',
    codeId: 'acc_02',
    code: 'DESIGNSYS-STUDENT-4412',
    userId: 'usr_student_01',
    userEmail: 'alex.rivera@example.com',
    courseId: 'course_02',
    redeemedAt: '2026-01-22T09:10:00Z',
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif_01',
    title: 'New Lesson Uploaded',
    message: 'Elena Vance published "Lesson 4: Running Chaos Drills" in Fullstack Cloud Architecture.',
    type: 'course',
    isRead: false,
    createdAt: '2026-09-21T18:45:00Z',
    actionUrl: 'learning/course_01/les_04_02',
  },
  {
    id: 'notif_02',
    title: 'Order Completed',
    message: 'Receipt #ORD-2026-9812 confirmed. You have permanent lifetime access.',
    type: 'payment',
    isRead: true,
    createdAt: '2026-09-15T11:59:00Z',
    actionUrl: 'orders',
  },
  {
    id: 'notif_03',
    title: 'Platform Maintenance Notice',
    message: 'Scheduled streaming CDN optimization this Saturday 02:00 UTC. No playback interruptions expected.',
    type: 'system',
    isRead: true,
    createdAt: '2026-09-10T08:00:00Z',
  },
];

export const mockAnalyticsData: Analytics = {
  totalWatchTimeHours: 18420,
  averageWatchDurationMinutes: 21.4,
  averageCompletionRatePercent: 68.5,
  totalCourseCompletions: 342,
  activeStudentsToday: 184,
  mostWatchedLessons: [
    {
      lessonId: 'les_01_01',
      lessonTitle: 'Stateless vs Authoritative Nodes',
      courseTitle: 'Fullstack Cloud Architecture',
      watchCount: 1240,
      averageWatchPercentage: 92.4,
      dropOffMinute: 22,
    },
    {
      lessonId: 'les_02_01',
      lessonTitle: 'The Dual-Write Problem & Transactional Outbox',
      courseTitle: 'Fullstack Cloud Architecture',
      watchCount: 1085,
      averageWatchPercentage: 86.1,
      dropOffMinute: 31,
    },
    {
      lessonId: 'les_201_01',
      lessonTitle: 'Mathematical Typography & Optical Harmony',
      courseTitle: 'UI Design Systems',
      watchCount: 960,
      averageWatchPercentage: 89.0,
      dropOffMinute: 25,
    },
    {
      lessonId: 'les_01_02',
      lessonTitle: 'Network Topologies, VPC Peering & Zero-Trust',
      courseTitle: 'Fullstack Cloud Architecture',
      watchCount: 915,
      averageWatchPercentage: 81.3,
      dropOffMinute: 27,
    },
  ],
  leastWatchedLessons: [
    {
      lessonId: 'les_04_02',
      lessonTitle: 'Running Chaos Drills and Automated Canary Rollbacks',
      courseTitle: 'Fullstack Cloud Architecture',
      watchCount: 210,
      averageWatchPercentage: 54.2,
      dropOffMinute: 14,
    },
    {
      lessonId: 'les_03_02',
      lessonTitle: 'Unified Design Token Pipeline and CSS Scoping',
      courseTitle: 'Fullstack Cloud Architecture',
      watchCount: 295,
      averageWatchPercentage: 58.7,
      dropOffMinute: 16,
    },
  ],
  dropOffPoints: [
    { minuteMark: 4, dropPercentage: 6.2, lessonTitle: 'Stateless vs Authoritative Nodes' },
    { minuteMark: 12, dropPercentage: 14.8, lessonTitle: 'Dual-Write Problem & Outbox' },
    { minuteMark: 18, dropPercentage: 22.1, lessonTitle: 'Distributed Sagas & Dead Letters' },
    { minuteMark: 28, dropPercentage: 11.4, lessonTitle: 'Network Topologies & VPCs' },
    { minuteMark: 35, dropPercentage: 8.5, lessonTitle: 'VPC Peering Deep Dive' },
  ],
  activityByHour: [
    { hourOrDay: '00:00', activeCount: 32 },
    { hourOrDay: '02:00', activeCount: 18 },
    { hourOrDay: '04:00', activeCount: 12 },
    { hourOrDay: '06:00', activeCount: 25 },
    { hourOrDay: '08:00', activeCount: 78 },
    { hourOrDay: '10:00', activeCount: 142 },
    { hourOrDay: '12:00', activeCount: 165 },
    { hourOrDay: '14:00', activeCount: 184 },
    { hourOrDay: '16:00', activeCount: 172 },
    { hourOrDay: '18:00', activeCount: 130 },
    { hourOrDay: '20:00', activeCount: 96 },
    { hourOrDay: '22:00', activeCount: 54 },
  ],
  activityByDay: [
    { hourOrDay: 'Mon', activeCount: 520 },
    { hourOrDay: 'Tue', activeCount: 680 },
    { hourOrDay: 'Wed', activeCount: 740 },
    { hourOrDay: 'Thu', activeCount: 710 },
    { hourOrDay: 'Fri', activeCount: 590 },
    { hourOrDay: 'Sat', activeCount: 430 },
    { hourOrDay: 'Sun', activeCount: 490 },
  ],
  countryDistribution: [
    { country: 'United States', countryCode: 'US', percentage: 42.5, activeStudents: 412 },
    { country: 'Germany', countryCode: 'DE', percentage: 14.2, activeStudents: 138 },
    { country: 'United Kingdom', countryCode: 'GB', percentage: 12.8, activeStudents: 124 },
    { country: 'Canada', countryCode: 'CA', percentage: 9.6, activeStudents: 93 },
    { country: 'India', countryCode: 'IN', percentage: 8.1, activeStudents: 79 },
    { country: 'Others (40+ nations)', countryCode: 'GL', percentage: 12.8, activeStudents: 124 },
  ],
};

export const mockStudentsList: Array<{
  id: string;
  name: string;
  email: string;
  avatarUrl: string;
  enrolledCoursesCount: number;
  totalWatchHours: number;
  overallCompletionRate: number;
  lastActiveAt: string;
  joinedAt: string;
  status: 'active' | 'inactive';
  enrolledCourses: {
    courseId: string;
    courseTitle: string;
    completionPercentage: number;
    lastWatchedLesson: string;
    lastActiveAt: string;
  }[];
}> = [
  {
    id: 'usr_student_01',
    name: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    enrolledCoursesCount: 2,
    totalWatchHours: 34.5,
    overallCompletionRate: 65,
    lastActiveAt: '2026-09-22T08:15:00Z',
    joinedAt: '2025-11-14T09:00:00Z',
    status: 'active',
    enrolledCourses: [
      {
        courseId: 'course_01',
        courseTitle: 'Fullstack Cloud Architecture',
        completionPercentage: 75,
        lastWatchedLesson: 'Container Lifecycle, Cold Starts & Probes',
        lastActiveAt: '2026-09-22T08:15:00Z',
      },
      {
        courseId: 'course_02',
        courseTitle: 'High-Performance UI Design Systems',
        completionPercentage: 55,
        lastWatchedLesson: 'Constructing Scalable Color Tokens',
        lastActiveAt: '2026-09-18T18:15:00Z',
      },
    ],
  },
  {
    id: 'usr_student_02',
    name: 'Marcus Chen',
    email: 'marcus.chen@techcorp.io',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    enrolledCoursesCount: 1,
    totalWatchHours: 18.2,
    overallCompletionRate: 40,
    lastActiveAt: '2026-09-21T14:20:00Z',
    joinedAt: '2026-02-10T14:15:00Z',
    status: 'active',
    enrolledCourses: [
      {
        courseId: 'course_01',
        courseTitle: 'Fullstack Cloud Architecture',
        completionPercentage: 40,
        lastWatchedLesson: 'The Dual-Write Problem & Outbox',
        lastActiveAt: '2026-09-21T14:20:00Z',
      },
    ],
  },
  {
    id: 'usr_student_03',
    name: 'Sarah Jenkins',
    email: 's.jenkins@enterprise.co',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=160&auto=format&fit=crop&q=80',
    enrolledCoursesCount: 1,
    totalWatchHours: 42.0,
    overallCompletionRate: 88,
    lastActiveAt: '2026-09-22T11:00:00Z',
    joinedAt: '2026-02-18T09:20:00Z',
    status: 'active',
    enrolledCourses: [
      {
        courseId: 'course_03',
        courseTitle: 'Applied AI Engineering & LLMOps',
        completionPercentage: 88,
        lastWatchedLesson: 'Latency-Bounded Routing Architectures',
        lastActiveAt: '2026-09-22T11:00:00Z',
      },
    ],
  },
  {
    id: 'usr_student_04',
    name: 'David Kim',
    email: 'david.kim@startup.xyz',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    enrolledCoursesCount: 1,
    totalWatchHours: 6.4,
    overallCompletionRate: 15,
    lastActiveAt: '2026-09-12T09:30:00Z',
    joinedAt: '2026-03-01T16:45:00Z',
    status: 'inactive',
    enrolledCourses: [
      {
        courseId: 'course_02',
        courseTitle: 'High-Performance UI Design Systems',
        completionPercentage: 15,
        lastWatchedLesson: 'Mathematical Typography',
        lastActiveAt: '2026-09-12T09:30:00Z',
      },
    ],
  },
  {
    id: 'usr_student_05',
    name: 'Priya Sharma',
    email: 'priya.s@devlead.org',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    enrolledCoursesCount: 2,
    totalWatchHours: 29.8,
    overallCompletionRate: 70,
    lastActiveAt: '2026-09-20T19:40:00Z',
    joinedAt: '2026-01-25T11:00:00Z',
    status: 'active',
    enrolledCourses: [
      {
        courseId: 'course_01',
        courseTitle: 'Fullstack Cloud Architecture',
        completionPercentage: 70,
        lastWatchedLesson: 'Module Federation vs Iframe Sandbox',
        lastActiveAt: '2026-09-20T19:40:00Z',
      },
    ],
  },
];
